# Generated by Django 4.0.6 on 2022-08-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
